fix (directchat): auto disconnect self once conn closed
status-im/nim-libp2p pull request #663
Opened 2021-11-26 01:25 UTC by emizzle

When closing a connection of clientA(using the command “/disconnect”), the connection is then closed on clientA’s side. However, the connection remained open on clientB and clientB could continue sending message to clientA and clientA would receive those messages.

This PR listens for a closing connection on clientB, then also closes clientB’s connection.

2021-11-26 06:51 UTC, Menduist requested changes
https://github.com/status-im/nim-libp2p/pull/662 needs to be merged first, blocking here in the meantime

2021-11-26 18:06 UTC, arnetheduck commented
this looks off  - generally, closing is a two-phase operation where one side initiates the close and the other side performs on receiving the close message and does cleanup (which might include sending more messages) then closes its side - automatic closing prevents that from happening.

2021-11-29 21:01 UTC, emizzle commented
> https://github.com/status-im/nim-libp2p/pull/662 needs to be merged first, blocking here in the meantime 

Because #662 was closed, this has been rebased on top of unstable.

2021-11-30 00:07 UTC, dryajov approved these changes
LGTM. This can be merged regardless of #662.

2021-11-30 00:08 UTC, dryajov commented on examples/directchat.nim
> +    defer: c.writeStdout $conn.peerId & " disconnected"
Just a word of caution with `defer`, which is known to fail when combined with `async`.

2021-12-02 12:45 UTC, Menduist approved these changes

2021-12-02 12:45 UTC, merged